services:
  api:
    container_name: mylibrary-backend-api
    image: aiod/mylibrary-backend-api:develop
    ports:
      - '8090:8000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: mylibrary-backend-db
    image: mongo:7.0
    ports:
      - 37017:27017
    volumes:
      - mylibrary-backend-db:/data/mylibrary-backend-db

volumes:
  mylibrary-backend-db:
