version: "3.8"

services:
  api:
    container_name: mylibrary-backend-api
    build: ./app
    volumes:
      - .:/code
    ports:
      - '8090:8000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: mylibrary-backend-db
    image: mongo
    ports:
      - 37017:27017
    volumes:
      - mylibrary-backend-db:/data/mylibrary-backend-db

volumes:
  mylibrary-backend-db: