version: '3.8'

services:
  api:
    container_name: mylibrary-backend-api
    build: ./app
    volumes:
      - .:/code
    ports:
      - '8090:8000'
    environment:
      - DB_URL=mongodb://db/myTestDB
    depends_on:
      - db
  db:
    container_name: mylibrary-backend-db
    image: mongo
    ports:
      - 37017:27017
    volumes:
      - db:/data/db

volumes:
  db: